[INFO 2023-06-13 14:23:51,104]-> Logs will be saved to /home/adriendutfoy/Desktop/Dev/MultiGraph/D:\Dev\THU-HyperG\examples\logs/2023-06-13--14-23-51/log.txt
[INFO 2023-06-13 14:23:51,105]-> Files in training will be saved in /home/adriendutfoy/Desktop/Dev/MultiGraph/D:\Dev\THU-HyperG\examples\logs/2023-06-13--14-23-51
[INFO 2023-06-13 14:23:51,105]-> Random seed is 1686633831
[INFO 2023-06-13 14:23:51,293]-> A new study created in RDB with name: no-name-c934edb2-adbe-4b55-899f-08eb75022201
[WARNING 2023-06-13 14:23:59,832]-> Trial 0 failed with parameters: {'k': 55, 'k_structured': 13, 'k_nearest': 98, 'k_cluster': 97, 'wu_kmeans': 8, 'wu_struct': 4, 'clusters': 539, 'adjacent_centers': 5, 'drop_rate': 0.21019594182871107, 'lr': 0.007895892122998948, 'weight_decay': 0.0015752365172876793} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/hypergraphs/hypergraph.py", line 71, in experiment
    return super().experiment(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/vertex_classification.py", line 83, in experiment
    return super().experiment(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/base.py", line 103, in experiment
    val_res = self.validate(self.data, model)
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/hypergraphs/hypergraph.py", line 108, in validate
    return super().validate(data, model)
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/vertex_classification.py", line 135, in validate
    ids = torch.tensor(ids).long().to(self.device)
KeyboardInterrupt
[WARNING 2023-06-13 14:23:59,833]-> Trial 0 failed with value None.
