[INFO 2023-05-10 18:18:16,657]-> Logs will be saved to /home/adriendutfoy/Desktop/Dev/MultiGraph/examples/logs/2023-05-10--18-18-16/log.txt
[INFO 2023-05-10 18:18:16,658]-> Files in training will be saved in /home/adriendutfoy/Desktop/Dev/MultiGraph/examples/logs/2023-05-10--18-18-16
[INFO 2023-05-10 18:18:16,658]-> Random seed is 0
[INFO 2023-05-10 18:18:16,659]-> A new study created in memory with name: no-name-447746b9-f9d9-474a-bbcb-cfc6da05e786
[WARNING 2023-05-10 18:18:16,659]-> Trial 0 failed with parameters: {} because of the following error: UnboundLocalError("local variable 'mod' referenced before assignment").
Traceback (most recent call last):
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/hypergraphs/hypergraph.py", line 71, in experiment
    return super().experiment(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/vertex_classification.py", line 83, in experiment
    return super().experiment(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/base.py", line 87, in experiment
    self.data["structure"] = self.structure_builder(trial).to(self.device)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/ascertain_classification.py", line 159, in structure_builder
    k = trial.suggest_int("k_"+str(mod), 2, 100)
UnboundLocalError: local variable 'mod' referenced before assignment
[WARNING 2023-05-10 18:18:16,660]-> Trial 0 failed with value None.
